text:
  buttons:
    tenant:
      water1: "Вода"
      water:
        hot_w2: "Горячая вода"
        cold_w2: "Холодная вода"
        choose_month: "Выбрать месяц"
        month_prefix: "M&o&n&t&h&W&a&t&e&r&"
      receipt1: "Квитанция"
      receipt:
        month2: "Месяц: 1-12"
        amount2: "Сумма RUB"
        receipt2: "Скрин оплаты"
        month_prefix: "M&o&n&t&h&R&e&c&e&i&p&t&"
      report1: "Сообщения о поломке"
    admin:
      rooms1: "Комнаты"
      room2: "N&u&m&b&e&r&"
      room:
        payment_prefix: "P&a&y&m&e&n&t&"
        show_scorer33: "Показания счётчика"
        show_scorerN4: "Все..."
        show_scorerB3: "Меньше..."
        show_payment33: "Квитанции"
        show_paymentN4: "Все...."
        show_paymentB3: "Меньше...."
        show_tenants3: "Квартиранты"
        remove_tenants4: "Удалить квартиранта"
      settings1: "Настройки"
      settings:
        edit2: "Добавить/удалить квартиру"
        edit:
          add_room3: "Добавить"
          remove_room3: "Удалить"
          removing4: "NumberDel"
          removing: 
            confirm_remove5: "Да"
        contacts2: "Telegram ремонтника"
        reminder2: "Напоминание"
        reminder_send3: "Отправить"
        reminder_edit3: "Редактировать"
  common_command:
    start: "start"
    cancel: "cancel"
    unknown: "unknown"
    back_but: "<<back"
    godmode: "godmode"
  common_message:
    hi: "Hi"
  response:
    start: "Привет! Я бот „Квартирант“.\nПомогаю сдавать в аренду квартиры.\n\n📩 ID: %d\nДля отмены любой операции используйте команду /cancel"
    cancel: "*~Операция отменена ↩~\r*"
    unknown_start: "Ссылка невалидная или её срок годности истёк. "
    unknown_cmd: "Я не знаю такой команды  :(\n"
    unknown_ms: "Я не знаю, как ответить :(\n"
    cache_ttl: "Пожалуйста, начните операцию заново."
    water1_first: "Данные сохранятся за %s месяц.\nВыберите какой параметр хотите внести первым."
    water1_sec: "Данные сохранятся после заполнения всех (двух) параметров.\nВнесите последний параметр."
    water2_inp: "Введите цифры с табло прибора учёта  (метры в кубе).\nК примеру: 34,56"
    water2_c_change: "💧Показания холодной воды в 〈%s〉 за  〈%s〉 успешно изменены."
    water2_h_change: "♨Показания горячей воды в 〈%s〉 за  〈%s〉 успешно изменены."
    water2_saved: "Счёт за воду успешно сохранён c параметрами:\n%s㎥ Hot♨, %s㎥ Cold💧, %s"
    receipt1_first: "Данные сохранятся после заполнения всех (трёх) параметров.\nВыберите, какой хотите внести первым."
    receipt1_sec: "Данные сохронятся после заполнения всех (трёх) параметров.\nВыберите какой хотите внести следующим."
    receipt1_third: "Данные сохронятся после заполнения всех (трёх) параметров.\nВнесите последний параметр."
    amount2_inp: "Введите в рублях сумму, которую вы внесли. К примеру: 4500"
    receipt2_saved: "Квитанция успешно сохранена c параметрами: %d ₽ , %s"
    report1_info: "По техническим вопросам пишите в личные сообщения [%s](tg://user?username=%s)"
    rooms1_list: "🏠 Список комнат⋮ "
    rooms1_nil: "⦰Список комнат пуст."
    settings1: "🔧⋯⋯⋯⋯⋯⇐Settings⇒⋯⋯⋯⋯⋯🔧"
    room2: "💠 № 〈%s〉 ⋮"
  constants:
    max_show_scorer: 5
    max_show_payment: 5