text:
  buttons:
    tenant:
      water1: "Вода"
      water:
        hot_w2: "Внести горячую воду"
        cold_w2: "Внести холодную воду"
      receipt1: "Квитанция"
      receipt:
        month2: "Месяц: 1-12"
        amount2: "Сумма оплаты"
        receipt2: "Скрин оплаты"
      report1: "Сообщения о поломке"
    admin:
      rooms1: "Комнаты"
      room2: "Number"
      room:
        show_scorer33: "Показания счётчика"
        show_scorerN4: "Все..."
        show_payment33: "Квитанции"
      settings1: "Настройки"
      settings:
        edit2: "Добавить/удалить квартиру"
        edit:
          add_room3: "Добавить"
          remove_room3: "Удалить"
          removing4: "NumberDel"
          removing: 
            confirm_remove5: "Да"
        contacts2: "Telegram ремонтника"
        reminder2: "Напоминание"
  response:
    start: "Привет! Я бот „Квартирант“.\nПомогаю сдавать в аренду квартиры.\n\n📩 ID: %d\nДля отмены любой операции используйте команду /cancel"
    unknown_cmd: "Я не знаю такой команды  :(\n"
    unknown_ms: "Я не знаю как ответить :(\n"
  common_command:
    start: "start"
    cancel: "cancel"
    unknown: "unknown"
    back_but: "<<back"
    godmode: "godmode"
  common_message:
    hi: "Hi"