text:
  buttons:
    tenant:
      water1: "Вода"
      water:
        hot_w2: "Внести горячую воду"
        cold_w2: "Внести холодную воду"
      receipt1: "Квитанция!"
      receipt:
        month2: "Месяц: 1-12"
        amount2: "Сумма оплаты"
        receipt2: "Скрин оплаты"
      report1: "Сообщения о поломке"
    admin:
      rooms1: "Комнаты"
      rooms:
        r2: "245"
      settings1: "Настройки"
      settings:
        edit2: "Добавить/удалить квартиру"
        contacts2: "Telegram ремонтника"
        reminder2: "Напоминание"
  response:
    start: "Привет! Я бот „Квартирант“.\nПомогаю сдавать в аренду квартиры.\n\nДля отмены любой операции используйте команду /cancel"
    unknown_cmd: "Я не знаю такой команды  :(\n"
    unknown_ms: "Я не знаю как ответить :(\n"