text:
  buttons:
    tenant:
      water1: "Вода"
      water:
        hot_w2: "Внести горячую воду"
        cold_w2: "Внести холодную воду"
      receipt1: "Квитанция"
      receipt:
        add_month2: "Месяц: 1-12"
        add_amount2: "Сумма оплаты"
        add_receipt2: "Скрин оплаты"
      report1: "Сообщения о поломке"
    admin:
      rooms1: "1,2,3,4"
  response:
    start: "Привет! Я бот „Квартирант“.\nПомогаю сдавать в аренду квартиры.\n\nДля отмены любой операции используйте команду /cancel"
    unknown_cmd: "Я не знаю такой команды  :(\n"
    unknown_ms: "Я не знаю как ответить :(\n"