name: CI

on:
  push:
    branches:
      - main

env:
  REGISTRY: "crpp6o1a47k42ls7uslj"
  IMAGE_NAME: "tg-bot-kvartirant"
  CONTAINER_NAME: "kvartirant"
  IMAGE_TAG: $GITHUB_SHA | head -c7

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Build container image
        run: docker build -t cr.yandex/$REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Log in to Yandex Cloud Container Registry with OAuth token
        run: echo ${{ secrets.YANDEXCLOUD_OAUTH_TOKEN }} | docker login --username oauth --password-stdin cr.yandex

      - name: Push image to Yandex Cloud Container Registry
        run: docker push cr.yandex/$REGISTRY/$IMAGE_NAME:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to Yandex Cloud via SSH action
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }} 
          envs: REGISTRY, IMAGE_NAME, CONTAINER_NAME, IMAGE_TAG, 
          script: |
            # Set env variables
            export TG_TOKEN=${{ secrets.TG_TOKEN }}
            export ACCESS_SECRET=${{ secrets.ACCESS_SECRET }}
            export GODMODE_SECRET=${{ secrets.GODMODE_SECRET }}

            # Log in to Yandex Cloud Container Registry with OAuth token
            echo ${{ secrets.YANDEXCLOUD_OAUTH_TOKEN }} | docker login --username oauth --password-stdin cr.yandex

            # Stop running containers & Remove old containers
            docker ps -q --filter "name=$CONTAINER_NAME" | grep -q . && \
            docker stop $CONTAINER_NAME && \
            docker rm -fv $CONTAINER_NAME

            # Pull image from Yandex Cloud Container Registry
            docker pull cr.yandex/$REGISTRY/$IMAGE_NAME:$IMAGE_TAG
            # Run a new container from a new image
            docker run -e TG_TOKEN -e ACCESS_SECRET -e GODMODE_SECRET -d -v kvartirant-db:/root \
            --restart always --publish 80:80 --name $CONTAINER_NAME \
            cr.yandex/$REGISTRY/$IMAGE_NAME:$IMAGE_TAG